version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install
  build:
    commands:
      - npx prisma generate
      - npm run build
artifacts:
  files:
    - '**/*'
  
